// AC_NO	AC_NAME_EN	AC_NAME_V1	CATEGORY
// 173	Nannilam	நன்னிலம்	SC
// 174	Tiruvarur	திருவாரூர்	SC
// 177	Tiruthuraipoondi	திருத்துறைப்பூண்டி	SC
// 178	Mannargudi	மன்னார்குடி	GEN

export const pollingStations = [
  {
    AC_NO: "173",
    POLL_NO: "1",
    POLL_NAME_EN: "Panchayat Union Primary School, Pillur",
    POLL_NAME_TA: "ஊராட்சி  ஒன்றிய துவக்கப்பள்ளி, பில்லூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "2",
    POLL_NAME_EN: "Panchayat Union Primary School, Pillur",
    POLL_NAME_TA: "ஊராட்சி  ஒன்றிய துவக்கப்பள்ளி, பில்லூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "3",
    POLL_NAME_EN: "Panchayat Union Middle School, Keeranur",
    POLL_NAME_TA: "ஊராட்சி  ஒன்றிய நடுநிலைப்பள்ளி, கீரனூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "4",
    POLL_NAME_EN: "Panchayat Union Middle School Annadhanapuram",
    POLL_NAME_TA: "ஊராட்சி  ஒன்றிய நடுநிலைப்பள்ளி, அன்னதானபுரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "5",
    POLL_NAME_EN: "Adi Dravidar Welfare School, Koothanur",
    POLL_NAME_TA: "ஆதிதிராவிடர் நலத்துவக்கப்பள்ளி, கூத்தனூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "6",
    POLL_NAME_EN: "Panchayat Union Primary School Sirupuliyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, சிறுபுலியூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "7",
    POLL_NAME_EN: "Panchayat Union Primary School Pavattakudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பாவாட்டக்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "8",
    POLL_NAME_EN: "Government Higher Secondary School (Adi Dravidar Welfare)",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, (ஆதிதிராவிடர் நலம்) ",
  },
  {
    AC_NO: "173",
    POLL_NO: "9",
    POLL_NAME_EN: "Adi Dravidar Welfare. Primary School Nedunkulam",
    POLL_NAME_TA: "ஆ.தி.ந. ஆரம்பப்பள்ளி, நெடுங்குளம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "10",
    POLL_NAME_EN: "Aided Middle School Thirukottaram",
    POLL_NAME_TA: "உதவிபெறும் நடுநிலைப்பள்ளி, திருக்கொட்டாரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "11",
    POLL_NAME_EN: "Aided Middle School Thirukottaram",
    POLL_NAME_TA: "உதவிபெறும் நடுநிலைப்பள்ளி, திருக்கொட்டாரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "12",
    POLL_NAME_EN: "Panchayat Union Primary School Thalaiyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, தலையூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "13",
    POLL_NAME_EN: "Government High School Kaduvangudi",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, கடுவங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "14",
    POLL_NAME_EN: "Panchayat Union Primary School, Pozhakudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, போழக்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "15",
    POLL_NAME_EN: "Panchayat Union Middle School Thirumeichur",
    POLL_NAME_TA: "ஊராட்சி  ஒன்றிய நடுநிலைப்பள்ளி, திருமெய்ச்சூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "16",
    POLL_NAME_EN: "Panchayat Union Primary School Maharajapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, மகாராஜபுரம் ",
  },
  {
    AC_NO: "173",
    POLL_NO: "17",
    POLL_NAME_EN: "Government High School Peralam",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, பேரளம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "18",
    POLL_NAME_EN: "Government High School Peralam",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, பேரளம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "19",
    POLL_NAME_EN: "Government High School Peralam",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, பேரளம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "20",
    POLL_NAME_EN: "Panchayat Union Primary School Kottur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கொட்டூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "21",
    POLL_NAME_EN: "Panchayat Union Primary School Kurungulam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, குருங்குளம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "22",
    POLL_NAME_EN: "Government High School, Kollapuram",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, கொல்லாபுரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "23",
    POLL_NAME_EN: "Panchayat Union Primary School Menangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, மேனாங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "24",
    POLL_NAME_EN: "Panchayat Union Primary School Upayavedantapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, உபயவேதாந்தபுரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "25",
    POLL_NAME_EN: "Panchayat Union Primary School Redtakudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ரெட்டக்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "26",
    POLL_NAME_EN: "Panchayat Union Primary School KovilThirumalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கோயில் திருமாளம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "27",
    POLL_NAME_EN: "Panchayat Union Primary School, Antakudi KovilThirumalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, அன்டக்குடி கோயில் திருமாளம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "28",
    POLL_NAME_EN: "Government High School Poonthottam Akarathirumalam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, பூந்தோட்டம் அகரதிருமாளம் ",
  },
  {
    AC_NO: "173",
    POLL_NO: "29",
    POLL_NAME_EN: "Government High School Poonthottam Akarathirumalam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, பூந்தோட்டம் அகரதிருமாளம் ",
  },
  {
    AC_NO: "173",
    POLL_NO: "30",
    POLL_NAME_EN: "Government High School Poonthottam Akarathirumalam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, பூந்தோட்டம் அகரதிருமாளம் ",
  },
  {
    AC_NO: "173",
    POLL_NO: "31",
    POLL_NAME_EN: "Panchayat Union Primary School Kothavasal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கொத்தவாசல்",
  },
  {
    AC_NO: "173",
    POLL_NO: "32",
    POLL_NAME_EN: "Panchayat Union Primary School seruvallur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, செருவலூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "33",
    POLL_NAME_EN: "Panchayat Union Primary School Alangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஆலங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "34",
    POLL_NAME_EN: "Mudikondan High School Mudikondan",
    POLL_NAME_TA: "முடிகொண்டான் உயர்நிலைப்பள்ளி, முடிகொண்டான்",
  },
  {
    AC_NO: "173",
    POLL_NO: "35",
    POLL_NAME_EN: "Mudikondan High School Mudikondan",
    POLL_NAME_TA: "முடிகொண்டான் உயர்நிலைப்பள்ளி, முடிகொண்டான்",
  },
  {
    AC_NO: "173",
    POLL_NO: "36",
    POLL_NAME_EN: "Government Higher Secondary School Nannilam",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, நன்னிலம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "37",
    POLL_NAME_EN: "Government Higher Secondary School Nannilam",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, நன்னிலம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "38",
    POLL_NAME_EN: "Government Higher Secondary School Nannilam",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, நன்னிலம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "39",
    POLL_NAME_EN: "Government Higher Secondary School Nannilam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, நன்னிலம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "40",
    POLL_NAME_EN: "Government Higher Secondary School Nannilam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, நன்னிலம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "41",
    POLL_NAME_EN: "Panchayat Union Middle School  Sannanallur Nannilam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, சன்னாநல்லூர்  நன்னிலம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "42",
    POLL_NAME_EN: "Panchayat Union Primary School Vatakudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, வடகுடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "43",
    POLL_NAME_EN: "Panchayat Union Middle School Achutamangalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைபள்ளி, அச்சுதமங்கலம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "44",
    POLL_NAME_EN: "Aided Primary School Thiruvanchiyam",
    POLL_NAME_TA: "உதவி பெறும் தொடக்கப்பள்ளி, வாழ்க்கை",
  },
  {
    AC_NO: "173",
    POLL_NO: "45",
    POLL_NAME_EN: "Islamic Aided Primary School, Senganur",
    POLL_NAME_TA: "இஸ்லாமிய உதவி பெறும் தொடக்கப்பள்ளி, சேங்கனூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "46",
    POLL_NAME_EN: "Aided Primary School Thiruvanchiyam",
    POLL_NAME_TA: "உதவி பெறும் தொடக்கப்பள்ளி, திருவாஞ்சியம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "47",
    POLL_NAME_EN: "Aided Primary School Thiruvanchiyam",
    POLL_NAME_TA: "உதவி பெறும் தொடக்கப்பள்ளி, திருவாஞ்சியம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "48",
    POLL_NAME_EN: "Panchayat Union Primary School Veedivitangan",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, வீதிவிடங்கன்",
  },
  {
    AC_NO: "173",
    POLL_NO: "49",
    POLL_NAME_EN: "Panchayat Union Primary School Thattathimoolai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, தட்டாத்திமூலை",
  },
  {
    AC_NO: "173",
    POLL_NO: "50",
    POLL_NAME_EN: "Aided Primary School Saliperi",
    POLL_NAME_TA: "உதவிப்பெறும் தொடக்கப்பள்ளி, சலிப்போி",
  },
  {
    AC_NO: "173",
    POLL_NO: "51",
    POLL_NAME_EN: "Panchayat Union Middle School Mapillaikuppam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, மாப்பிள்ளைக்குப்பம் ",
  },
  {
    AC_NO: "173",
    POLL_NO: "52",
    POLL_NAME_EN: "Panchayat Union Primary School, Anaikuppam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஆனைக்குப்பம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "53",
    POLL_NAME_EN: "Government Adi Dravidar Welfare School, Thirukandeeswaram",
    POLL_NAME_TA: "அரசினர் ஆதிதிராவிடர் நலப்பள்ளி, திருக்கண்டீஸ்வரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "54",
    POLL_NAME_EN: "Government High School Panangudi",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, பனங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "55",
    POLL_NAME_EN: "Aided Primary School Kuvalaikkal",
    POLL_NAME_TA: "உதவி பெறும் தொடக்கப்பள்ளி, குவளைக்கால்",
  },
  {
    AC_NO: "173",
    POLL_NO: "56",
    POLL_NAME_EN: "Panchayat Union Primary School Visalur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, விசலூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "57",
    POLL_NAME_EN: "Panchayat Union Primary School, Sorakudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, சொரக்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "58",
    POLL_NAME_EN: "Panchayat Union Primary School, Moongilgudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, மூங்கில்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "59",
    POLL_NAME_EN: "Panchayat Union Primary School Kongarayanallur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, கொங்கராயநல்லூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "60",
    POLL_NAME_EN: "Government High School Ambal",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, அம்பல்",
  },
  {
    AC_NO: "173",
    POLL_NO: "61",
    POLL_NAME_EN: "Government High School Ambal",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, அம்பல்",
  },
  {
    AC_NO: "173",
    POLL_NO: "62",
    POLL_NAME_EN: "Government High School Ganapathipuram Idayathangudi",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, கணபதிபுரம் இடையாத்தங்குடி ",
  },
  {
    AC_NO: "173",
    POLL_NO: "63",
    POLL_NAME_EN: "Panchayat Union Primary School, Airwadi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஏர்வாடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "64",
    POLL_NAME_EN: "Panchayat Union Primary School Seshamoolai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, சேஷமூலை",
  },
  {
    AC_NO: "173",
    POLL_NO: "65",
    POLL_NAME_EN: "Panchayat Union Primary School Alandur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஆலந்தூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "66",
    POLL_NAME_EN: "Rafiq Aided Primary School Panangattur Konthagai",
    POLL_NAME_TA: "ரபீக் உதவி பெறும் தொடக்கப்பள்ளி, பனங்காட்டூர் கொந்தகை",
  },
  {
    AC_NO: "173",
    POLL_NO: "67",
    POLL_NAME_EN: "Souriraja Aided Primary School  Agara Konthagai",
    POLL_NAME_TA: "சௌரிராஜா உதவிபெறும் தொடக்கப்பள்ளி, அகரக்கொந்தகை",
  },
  {
    AC_NO: "173",
    POLL_NO: "68",
    POLL_NAME_EN: "Panchayat Union Middle School  Pirakkiramam Katumavadi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைபள்ளி, பிராக்கிராமம் கட்டுமாவடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "69",
    POLL_NAME_EN: "Government Higher Secondary School  Thettacheri",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, திட்டச்சோி ",
  },
  {
    AC_NO: "173",
    POLL_NO: "70",
    POLL_NAME_EN: "Government Higher Secondary School  Thettacheri",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, திட்டச்சோி",
  },
  {
    AC_NO: "173",
    POLL_NO: "71",
    POLL_NAME_EN: "Government Higher Secondary School  Thettacheri",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, திட்டச்சோி",
  },
  {
    AC_NO: "173",
    POLL_NO: "72",
    POLL_NAME_EN: "Government Higher Secondary School  Thettacheri",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, திட்டச்சோி",
  },
  {
    AC_NO: "173",
    POLL_NO: "73",
    POLL_NAME_EN: "Panchayat Union Primary School Seeyathamangai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, சீயாத்தமங்கை",
  },
  {
    AC_NO: "173",
    POLL_NO: "74",
    POLL_NAME_EN: "Panchayat Union Primary School Pantaravadai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, பண்டாரவாடை",
  },
  {
    AC_NO: "173",
    POLL_NO: "75",
    POLL_NAME_EN: "Panchayat Union Primary School Keezhapolakam ",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, கீழப்போலகம் (ஊ)",
  },
  {
    AC_NO: "173",
    POLL_NO: "76",
    POLL_NAME_EN: "Panchayat Union Primary School Guruvadi Polagam (P)",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, குருவாடி போலகம் (ஊ)",
  },
  {
    AC_NO: "173",
    POLL_NO: "77",
    POLL_NAME_EN: "Panchayat Union Primary School Tiruppukalur Polagam (P)",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, திருப்புகளூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "78",
    POLL_NAME_EN: "Panchayat Union Primary School Tiruppukalur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, திருப்புகளூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "79",
    POLL_NAME_EN: "Panchayat Union Primary School Enangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஏனங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "80",
    POLL_NAME_EN: "Panchayat Union Primary School Enangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஏனங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "81",
    POLL_NAME_EN: "Panchayat Union Primary School Puthagaram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, புத்தகரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "82",
    POLL_NAME_EN: "Panchayat Union Primary School Puthagaram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, புத்தகரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "83",
    POLL_NAME_EN: "Panchayat Union Primary School Adalaiyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஆதலையூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "84",
    POLL_NAME_EN: "Panchayat Union Middle School Vadakarai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, வடகரை",
  },
  {
    AC_NO: "173",
    POLL_NO: "85",
    POLL_NAME_EN: "Panchayat Union Middle School Kottur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கோட்டூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "86",
    POLL_NAME_EN: "Panchayat Union Middle School Kottur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கோட்டூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "87",
    POLL_NAME_EN: "Government High School, Thirukannapuram",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, திருக்கண்ணபுரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "88",
    POLL_NAME_EN: "Panchayat Union Primary School Thiruchengattakudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, திருச்செங்காட்டக்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "89",
    POLL_NAME_EN: "Panchayat Union Primary School Thirumarugal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, திருமருகல்",
  },
  {
    AC_NO: "173",
    POLL_NO: "90",
    POLL_NAME_EN: "Panchayat Union Primary School Thirumarugal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, திருமருகல்",
  },
  {
    AC_NO: "173",
    POLL_NO: "91",
    POLL_NAME_EN: "Panchayat Union Primary School Segal Thirumarugal (P)",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, சேகல் திருமருகல் (ஊ)",
  },
  {
    AC_NO: "173",
    POLL_NO: "92",
    POLL_NAME_EN: "Panchayat Union Primary School, Eravancheri",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஏரவாஞ்சோி",
  },
  {
    AC_NO: "173",
    POLL_NO: "93",
    POLL_NAME_EN: "Panchayat Union Primary School Marungur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, மருங்கூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "94",
    POLL_NAME_EN: "Nadesaya Aided Middle School, Melapoothanur",
    POLL_NAME_TA: "நடேசய்யா உதவி பெறும் நடுநிலைப்பள்ளி, மேலப்பூதனூர் ",
  },
  {
    AC_NO: "173",
    POLL_NO: "95",
    POLL_NAME_EN: "Panchayat Union Primary School Vergudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, விற்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "96",
    POLL_NAME_EN: "Panchayat Union Primary School Raranthimangalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ராராந்திமங்கலம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "97",
    POLL_NAME_EN: "Government High School Vazhkudi",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, வாழ்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "98",
    POLL_NAME_EN: "Panchayat Union Primary School, Kangalancheri",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, கங்களாஞ்சோி",
  },
  {
    AC_NO: "173",
    POLL_NO: "99",
    POLL_NAME_EN: "Panchayat Union Primary School Karaiyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, காரையூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "100",
    POLL_NAME_EN: "Panchayat Union Primary School Thirupayathangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, திருபயத்தங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "101",
    POLL_NAME_EN: "Panchayat Union Primary School Kottarakkudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, கொட்டாரக்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "102",
    POLL_NAME_EN: "Panchayat Union Primary School Kutthalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, குத்தாலம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "103",
    POLL_NAME_EN: "Panchayat Union Primary School Narimanam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, நரிமணம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "104",
    POLL_NAME_EN:
      "Panchayat Union Primary School, Boothangudi, Uttamacholapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, பூதங்குடி உத்தமசோழபுரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "105",
    POLL_NAME_EN: "Sri Rajeshwari Aided Primary School  Panangudi",
    POLL_NAME_TA: "ஸ்ரீ ராஜேஸ்வரி உதவி பெறும் தொடக்கப்பள்ளி, பனங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "106",
    POLL_NAME_EN: "Panchayat Union Primary School, Kondaiyaniruppu, Ilaiyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, கொண்டையானிருப்பு இலையூர்  ",
  },
  {
    AC_NO: "173",
    POLL_NO: "107",
    POLL_NAME_EN: "Semmangudi Higher Secondary School Semmangudi",
    POLL_NAME_TA: "செம்மங்குடி மேல்நிலைபள்ளி, செம்மங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "108",
    POLL_NAME_EN: "Panchayat Union Primary School, Arasavanagadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, அரசவனங்காடு",
  },
  {
    AC_NO: "173",
    POLL_NO: "109",
    POLL_NAME_EN: "Panchayat Union Primary School Keerangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கீரங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "110",
    POLL_NAME_EN: "Panchayat Union Primary School Nagakkudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, நாகக்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "111",
    POLL_NAME_EN: "Panchayat Union Middle School Ayyampettai Manakkal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, அய்யம்பேட்டை மணக்கால் ",
  },
  {
    AC_NO: "173",
    POLL_NO: "112",
    POLL_NAME_EN: "Panchayat Union Middle School Ayyampettai Manakkal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, அய்யம்பேட்டை மணக்கால் ",
  },
  {
    AC_NO: "173",
    POLL_NO: "113",
    POLL_NAME_EN: "Vivekananda Aided Primary School, Kapanamangalam",
    POLL_NAME_TA: "விவேகானந்தா உதவி பெறும் தொடக்கப்பள்ளி, காப்பணாமங்கலம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "114",
    POLL_NAME_EN: "Panchayat Union Primary School Keerathangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, கீரத்தங்குடி",
  },
  {
    AC_NO: "173",
    POLL_NO: "115",
    POLL_NAME_EN: "Panchayat Union Primary School Sellur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, செல்லூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "116",
    POLL_NAME_EN: "Panchayat Union Primary School Thirukalampur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, திருகளம்பூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "117",
    POLL_NAME_EN: "Panchayat Union Primary School Poongavoor",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, பூங்காவூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "118",
    POLL_NAME_EN: "Panchayat Union Primary School Neikuppai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, நெய்க்குப்பை",
  },
  {
    AC_NO: "173",
    POLL_NO: "119",
    POLL_NAME_EN: "Panchayat Union Middle School, Enkan",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, என்கண் ",
  },
  {
    AC_NO: "173",
    POLL_NO: "120",
    POLL_NAME_EN: "Panchayat Union Middle School Vadakandam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, வடகண்டம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "121",
    POLL_NAME_EN: "Panchayat Union Primary School Vandambalai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, வண்டாம்பாளை",
  },
  {
    AC_NO: "173",
    POLL_NO: "122",
    POLL_NAME_EN: "Panchayat Union Primary School Perumpugalur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, பெரும்புகளூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "123",
    POLL_NAME_EN: "Panchayat Union Primary School Thirukannamangai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, திருக்கண்ணமங்கை",
  },
  {
    AC_NO: "173",
    POLL_NO: "124",
    POLL_NAME_EN: "Panchayat Union Middle School Abhivirtheeswaram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, அபிவிருத்தீஸ்வரம்",
  },
  {
    AC_NO: "173",
    POLL_NO: "125",
    POLL_NAME_EN: "Government Adi Dravidar Welfare Primary School, Pathur",
    POLL_NAME_TA: "அரசினர் ஆதிதிராவிடர் நலதொடக்கப்பள்ளி, பத்தூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "126",
    POLL_NAME_EN: "Panchayat Union Middle School Kattur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, காட்டூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "127",
    POLL_NAME_EN: "Panchayat Union Middle School Akarathirunallur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, அகரத்திருநல்லூர்",
  },
  {
    AC_NO: "173",
    POLL_NO: "128",
    POLL_NAME_EN: "Panchayat Union Middle School Pavithramanickam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, பவித்திரமாணிக்கம் ",
  },
  {
    AC_NO: "173",
    POLL_NO: "129",
    POLL_NAME_EN: "Panchayat Union Middle School Pavithramanickam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, பவித்திரமாணிக்கம் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "1",
    POLL_NAME_EN: "St. Francis Middle School, Melkarai",
    POLL_NAME_TA: "செயின்ட் ப்ரான்சிஸ் நடுநிலைப்பள்ளி, மேல்கரை ",
  },
  {
    AC_NO: "174",
    POLL_NO: "2",
    POLL_NAME_EN: "Panchayat Union Elementary School, Koradacherry",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கொரடாச்சேரி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "3",
    POLL_NAME_EN: "Government Girls' High School, Koradacherry",
    POLL_NAME_TA: "அரசினர் மகளிர்  உயர்நிலைப்பள்ளி, கொரடாச்சேரி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "4",
    POLL_NAME_EN: "Government Girls' High School, Koradacherry",
    POLL_NAME_TA: "அரசினர் மகளிர்  உயர்நிலைப்பள்ளி, கொரடாச்சேரி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "5",
    POLL_NAME_EN: "Vinayaka Aided Middle School, Aykudi",
    POLL_NAME_TA: "விநாயகா உதவி பெறும் நடுநிலைப்பள்ளி, ஆய்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "6",
    POLL_NAME_EN: "Panchayat Union Elementary School, Aykudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஆய்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "7",
    POLL_NAME_EN: "Panchayat Union Primary School, Atthichozhamangalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, அத்திச்சோழமங்கலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "8",
    POLL_NAME_EN: "Panchayat Union Primary School, Kavanur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, காவனூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "9",
    POLL_NAME_EN: "Panchayat Union Primary School, Ammaiyappan",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, அம்மையப்பன்",
  },
  {
    AC_NO: "174",
    POLL_NO: "10",
    POLL_NAME_EN: "Government Higher Secondary School, Ammaiyappan\r\n",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, அம்மையப்பன்",
  },
  {
    AC_NO: "174",
    POLL_NO: "11",
    POLL_NAME_EN: "Panchayat Union Primary School, Anaivadapathy, Ammaiyappan",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஆனைவடாபதி அம்மையப்பன்",
  },
  {
    AC_NO: "174",
    POLL_NO: "12",
    POLL_NAME_EN: "Government Primary School, Thevarkandanallur",
    POLL_NAME_TA: "அரசினர் தொடக்கப்பள்ளி, தேவர்கண்டநல்லூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "13",
    POLL_NAME_EN: "Government High School Kulikarai, Perundarakkudi",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, குளிக்கரை பெருந்தரக்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "14",
    POLL_NAME_EN: "Government High School Kulikarai, Perundarakkudi",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, குளிக்கரை பெருந்தரக்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "15",
    POLL_NAME_EN: "Panchayat Union Primary School, Perundarakkudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, பெருந்தரக்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "16",
    POLL_NAME_EN: "Panchayat Union Primary School, Thiagarajapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, தியாகராஜபுரம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "17",
    POLL_NAME_EN:
      "Panchayat Union Primary School, Cholacherry, Melathirumathikunnam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, சோழச்சேரி  மேலதிருமதிக்குண்ணம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "18",
    POLL_NAME_EN: "Panchayat Union Primary School, Perumalakaram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, பெருமாளகரம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "19",
    POLL_NAME_EN: "Panchayat Union Primary School, Kalathur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, களத்தூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "20",
    POLL_NAME_EN: "Panchayat Union Primary School, Kalathur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, களத்தூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "21",
    POLL_NAME_EN: "Panchayat Union Primary School, Thiruvidaivasal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, திருவிடைவாசல்",
  },
  {
    AC_NO: "174",
    POLL_NO: "22",
    POLL_NAME_EN: "Panchayat Union Middle School, Athikadai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, அத்திக்கடை",
  },
  {
    AC_NO: "174",
    POLL_NO: "23",
    POLL_NAME_EN: "Panchayat Union Middle School, Athikadai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, அத்திக்கடை",
  },
  {
    AC_NO: "174",
    POLL_NO: "24",
    POLL_NAME_EN: "Panchayat Union Primary School, Musiriyam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, முசிரியம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "25",
    POLL_NAME_EN: "Government High School, Kankotthavanitham",
    POLL_NAME_TA: "அரசு உயர்நிலைப்பள்ளி, கண்கொடுத்தவணிதம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "26",
    POLL_NAME_EN:
      "Panchayat Union Primary School, Tirupanipettai, Melathirathikunnam",
    POLL_NAME_TA:
      "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, திருப்பணிப்பேட்டை மேலதிருமதிக்குண்ணம் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "27",
    POLL_NAME_EN: "Panchayat Union Primary School, Erukkattur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஏருக்காட்டூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "28",
    POLL_NAME_EN: "Panchayat Union Primary School, Erukkattur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஏருக்காட்டூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "29",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Middle School, Thandalai",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, தண்டலை",
  },
  {
    AC_NO: "174",
    POLL_NO: "30",
    POLL_NAME_EN: "Bava Gopalsamy Municipal Primary School, Thiruvarur",
    POLL_NAME_TA: "பாவா கோபால்சாமி நகராட்சி தொடக்கப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "31",
    POLL_NAME_EN: "Bava Gopalsamy Municipal Primary School, Thiruvarur",
    POLL_NAME_TA: "பாவா கோபால்சாமி நகராட்சி தொடக்கப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "32",
    POLL_NAME_EN: "New Bharat English School, Thiruvarur",
    POLL_NAME_TA: "நியூ பாரத் ஆங்கிலப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "33",
    POLL_NAME_EN: "Kodikalpalayam Government High School, Thiruvarur",
    POLL_NAME_TA: "கொடிக்கால்பாளையம்  அரசு உயர்நிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "34",
    POLL_NAME_EN: "Municipal Primary School, Thiruvarur",
    POLL_NAME_TA: "நகராட்சி தொடக்கப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "35",
    POLL_NAME_EN: "Municipal Primary School, Thiruvarur",
    POLL_NAME_TA: "நகராட்சி  தொடக்கப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "36",
    POLL_NAME_EN: "Venkateswara Aided Primary School, Thiruvarur",
    POLL_NAME_TA: "வெங்கடேஸ்வரா உதவிபெறும் தொடக்கப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "37",
    POLL_NAME_EN: "Gowriswamy Memorial Municipal Middle School, Thiruvarur",
    POLL_NAME_TA: "கௌரிசாமி நினைவு நகராட்சி நடுநிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "38",
    POLL_NAME_EN: "SS Aided Middle School, Thiruvarur",
    POLL_NAME_TA: "எஸ் எஸ்  உதவிபெறும் நடுநிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "39",
    POLL_NAME_EN: "Kamalambika Aided Primary School, Thiruvarur",
    POLL_NAME_TA: "கமலாம்பிகா உதவிபெறும் தொடக்கப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "40",
    POLL_NAME_EN: "Sabapathi Mudaliar Municipal Middle School, Thiruvarur",
    POLL_NAME_TA: "சபாபதி முதலியார் நகராட்சி நடுநிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "41",
    POLL_NAME_EN:
      "G. Renganatha Mudaliar Girls' Higher Secondary School, Thiruvarur",
    POLL_NAME_TA: "ஜி ரெங்கநாத முதலியார் பெண்கள் மேல் நிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "42",
    POLL_NAME_EN: "Gowriswamy Memorial Middle School, Thiruvarur",
    POLL_NAME_TA: "கௌரிசாமி நினைவு நடுநிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "43",
    POLL_NAME_EN: "Saivaprakasha Aided Middle School, Thiruvarur",
    POLL_NAME_TA: "சைவப்பிரகாச உதவிபெறும்நடுநிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "44",
    POLL_NAME_EN: "Saivaprakasha Aided Middle School, Thiruvarur",
    POLL_NAME_TA: "சைவப்பிரகாச உதவிபெறும்நடுநிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "45",
    POLL_NAME_EN:
      "G. Renganatha Mudaliar Girls' Higher Secondary School, Thiruvarur",
    POLL_NAME_TA: "ஜி ரெங்கநாத முதலியார் பெண்கள் மேல் நிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "46",
    POLL_NAME_EN: "Municipal Middle School, Thiruvarur",
    POLL_NAME_TA: "நகராட்சி நடுநிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "47",
    POLL_NAME_EN: "Moses Middle School, Thiruvarur",
    POLL_NAME_TA: "மோசஸ் நடுநிலைப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "48",
    POLL_NAME_EN: "Panchayat Union Office Thiruvarur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய அலுவலகம் திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "49",
    POLL_NAME_EN: "Panchayat Union Office Thiruvarur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய அலுவலகம் திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "50",
    POLL_NAME_EN: "Raman Aided Primary School, Thiruvarur",
    POLL_NAME_TA: "ராமன் உதவிபெறும் தொடக்கப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "51",
    POLL_NAME_EN: "KTR Municipal Elementary School, Thiruvarur",
    POLL_NAME_TA: "கேடி ஆர்  நகராட்சி  துவக்கப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "52",
    POLL_NAME_EN: "KTR Municipal Elementary School, Thiruvarur",
    POLL_NAME_TA: "கேடி ஆர்  நகராட்சி  துவக்கப்பள்ளி, திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "53",
    POLL_NAME_EN: "Thiru Vi Ka Government Arts College Thiruvarur",
    POLL_NAME_TA: "திரு வி க  அரசு கலைக் கல்லூரி திருவாரூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "54",
    POLL_NAME_EN:
      "Thiruvarur Panchayat Union Elementary School Keelakavathukudi",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கீழகாவாதுக்குடி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "55",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Middle School, Palayavalam",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, பழையவலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "56",
    POLL_NAME_EN: "Adi Dravidar Welfare School, Serukudi",
    POLL_NAME_TA: "ஆதிதிராவிடர் நலப்பள்ளி, செருகுடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "57",
    POLL_NAME_EN: "Panchayat Union Elementary School, Vaipur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, வைப்பூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "58",
    POLL_NAME_EN: "Panchayat Union  Elementary School, Thiruvadhiraimangalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, திருவாதிரைமங்கலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "59",
    POLL_NAME_EN: "Government Higher Secondary School, Thiruvadhiraimangalam",
    POLL_NAME_TA: "அரசு மேல்நிலைப்பள்ளி, திருவாதிரைமங்கலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "60",
    POLL_NAME_EN: "Panchayat Union Elementary School, Amur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஆமூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "61",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School, Odacherry",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஓடாச்சேரி  ",
  },
  {
    AC_NO: "174",
    POLL_NO: "62",
    POLL_NAME_EN: "Thiruvarur Municipal Union Middle School, Kallikudi",
    POLL_NAME_TA: "திருவாரூர் நகராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கள்ளிக்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "63",
    POLL_NAME_EN: "Adi Dravidian Welfare School, Palavanakudi",
    POLL_NAME_TA: "ஆதிதிராவிட நலப்பள்ளி, பழவனக்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "64",
    POLL_NAME_EN: "Government High School Adiyakkamangalam",
    POLL_NAME_TA: "அரசு உயர்நிலைப்பள்ளி, அடியக்கமங்கலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "65",
    POLL_NAME_EN:
      "Thiruvarur Panchayat Union Elementary School, Adiyakkamangalam",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, அடியக்கமங்கலம் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "66",
    POLL_NAME_EN:
      "Thiruvarur Panchayat Union Elementary School, Adiyakkamangalam",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, அடியக்கமங்கலம் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "67",
    POLL_NAME_EN:
      "Thiruvarur Panchayat Union Elementary School, Adiyakkamangalam",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, அடியக்கமங்கலம் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "68",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School, Semangalam",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, சேமங்கலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "69",
    POLL_NAME_EN: "Government High School Alivalam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, அலிவலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "70",
    POLL_NAME_EN: "Government High School Alivalam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, அலிவலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "71",
    POLL_NAME_EN: "Government High School, Pulivalam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, புலிவலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "72",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School Pulivalam",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, புலிவலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "73",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School Pulivalam",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, புலிவலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "74",
    POLL_NAME_EN:
      "Government Adi Dravidar Welfare Elementary School, Velangudi",
    POLL_NAME_TA: "அரசினர் ஆதிதிராவிடர் நலதுவக்கப்பள்ளி, வேலங்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "75",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School Perungudi",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பெருங்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "76",
    POLL_NAME_EN:
      "Thiruvarur Panchayat Union Elementary School Kalyana Mahadevi",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கல்யாணமகாதேவி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "77",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School Kudur",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கூடூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "78",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School Kudur",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கூடூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "79",
    POLL_NAME_EN: "Aided Primary School Kariangudi",
    POLL_NAME_TA: "உதவிபெறும் ஆரம்பப்பள்ளி, காரியங்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "80",
    POLL_NAME_EN: "Krishna Aided Middle School, Thappalambuliyur",
    POLL_NAME_TA: "கிருஷ்ணா உதவிபெறும் நடுநிலைப்பள்ளி, தப்பாளம்புலியூர் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "81",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School, Puduphathur",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, புதுப்பத்தூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "82",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Middle School, Mangudi",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, மாங்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "83",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Middle School, Mangudi",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, மாங்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "84",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Middle School, Vadakarai",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, வடகரை",
  },
  {
    AC_NO: "174",
    POLL_NO: "85",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School, Athur",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஆத்தூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "86",
    POLL_NAME_EN: "Government Higher Secondary School, Thiruneiper",
    POLL_NAME_TA: "அரசு மேல்நிலைப்பள்ளி, திருநெய்ப்போ்",
  },
  {
    AC_NO: "174",
    POLL_NO: "87",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School, Thiruneiper",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, திருநெய்ப்போ்",
  },
  {
    AC_NO: "174",
    POLL_NO: "88",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School, Thiruneiper",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, திருநெய்ப்போ்",
  },
  {
    AC_NO: "174",
    POLL_NO: "89",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School, Veppathangudi",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, வேப்பத்தாங்குடி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "90",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Elementary School Pinnavasal",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பின்னவாசல்",
  },
  {
    AC_NO: "174",
    POLL_NO: "91",
    POLL_NAME_EN:
      "Tiruvarur Panchayat Union Elementary School Umamaheswarapuram",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, உமாமகேஸ்வரபுரம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "92",
    POLL_NAME_EN: "Tiruvarur Panchayat Union Elementary School, Puthur",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, புதூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "93",
    POLL_NAME_EN: "Thiruvarur Panchayat Union Middle School, Thirukaravasal",
    POLL_NAME_TA: "திருவாரூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, திருக்காரவாசல்  ",
  },
  {
    AC_NO: "174",
    POLL_NO: "94",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Anaimangalam",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஆணைமங்கலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "95",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Okkur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஓக்கூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "96",
    POLL_NAME_EN: "Kilvelur Panchayat Union Middle School, Venkitangal",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, வெங்கிடங்கால் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "97",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School Vadakarai",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, வடகரை",
  },
  {
    AC_NO: "174",
    POLL_NO: "98",
    POLL_NAME_EN: "Kilvelur Panchayat Union Middle School, Kokoor",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கோகூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "99",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School Akarakadambanur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, அகரகடம்பனூர் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "100",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School Akarakadambanur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, அகரகடம்பனூர",
  },
  {
    AC_NO: "174",
    POLL_NO: "101",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Eravancherry",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, எரவாஞ்சேரி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "102",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Gurumanangudi",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, குருமணாங்குடி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "103",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Gurumanangudi",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, குருமணாங்குடி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "104",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Athipuliyur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, அத்திபுலியூர் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "105",
    POLL_NAME_EN: "Government High School Kurukkathi",
    POLL_NAME_TA: "அரசுஉயர்நிலைப்பள்ளி, குருக்கத்தி",
  },
  {
    AC_NO: "174",
    POLL_NO: "106",
    POLL_NAME_EN: "Thiru Anjuwattathamman Girls' High School, Kilvelur",
    POLL_NAME_TA: "திருஅஞ்சுவட்டத்தம்மன் பெண்கள் உயர்நிலைப்பள்ளி, கீழ்வேளூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "107",
    POLL_NAME_EN: "Kilvelur Panchayat Union Middle School Kilvelur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கீழ்வேளூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "108",
    POLL_NAME_EN: "Government Boys Higher Secondary School, Kilvelur",
    POLL_NAME_TA: "அரசு ஆண்கள் மேல்நிலைப்பள்ளி, கீழ்வேளூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "109",
    POLL_NAME_EN: "Kilvelur Panchayat Union Middle School, Thirukannangudi",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, திருக்கண்ணங்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "110",
    POLL_NAME_EN: "Aided Primary School Pattamangalam",
    POLL_NAME_TA: "உதவிபெறும் துவக்கப்பள்ளி, பட்டமங்கலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "111",
    POLL_NAME_EN: "Kilvelur Panchayat Union Middle School, Koothur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கூத்தூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "112",
    POLL_NAME_EN: "Aided Elementary School, Cherunallur",
    POLL_NAME_TA: "உதவிபெறும் துவக்கப்பள்ளி, செருநல்லூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "113",
    POLL_NAME_EN: "Aided Elementary School Kakkalani",
    POLL_NAME_TA: "உதவிபெறும் துவக்கப்பள்ளி, காக்கழனி",
  },
  {
    AC_NO: "174",
    POLL_NO: "114",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Iluppur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, இலுப்பூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "115",
    POLL_NAME_EN: "Government Higher Secondary School Thevur",
    POLL_NAME_TA: "அரசு மேல்நிலைப்பள்ளி, தேவூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "116",
    POLL_NAME_EN: "Government Higher Secondary School Thevur",
    POLL_NAME_TA: "அரசு மேல்நிலைப்பள்ளி, தேவூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "117",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School Radhamangalam",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ராதாமங்கலம் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "118",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Irukkai",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, இருக்கை",
  },
  {
    AC_NO: "174",
    POLL_NO: "119",
    POLL_NAME_EN: "Keelvelur Panchayat Union Elementary School, Venmani",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, வெண்மணி",
  },
  {
    AC_NO: "174",
    POLL_NO: "120",
    POLL_NAME_EN: "Aided Middle School Manalur",
    POLL_NAME_TA: "உதவிபெறும் நடுநிலைப்பள்ளி, மணலூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "121",
    POLL_NAME_EN: "Kilvelur Panchayat Union Middle School Andhakudi",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, ஆந்தக்குடி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "122",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School Sikar",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, சிகார்",
  },
  {
    AC_NO: "174",
    POLL_NO: "123",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Kurathangudi",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கூரத்தாங்குடி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "124",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Manalur 67",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, மாணலூர் 67",
  },
  {
    AC_NO: "174",
    POLL_NO: "125",
    POLL_NAME_EN: "Kilvelur Panchayat Union Middle School, Killukudi",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கிள்ளுக்குடி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "126",
    POLL_NAME_EN: "Aided Elementary School, Anakudi",
    POLL_NAME_TA: "உதவிபெறும் துவக்கப்பள்ளி, அணக்குடி",
  },
  {
    AC_NO: "174",
    POLL_NO: "127",
    POLL_NAME_EN: "Kilvelur Panchayat Union Primary School, Vandalur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, வண்டலூர்",
  },
  {
    AC_NO: "174",
    POLL_NO: "128",
    POLL_NAME_EN: "Kilvelur Panchayat Union Middle School, Satiyakudi",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, சாட்டியக்குடி ",
  },
  {
    AC_NO: "174",
    POLL_NO: "129",
    POLL_NAME_EN: "Kilvelur Panchayat Union Middle School, Koilkannapur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கோயில்கண்ணாப்பூர் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "130",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School Adamangalam",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஆதமங்கலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "131",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School, Kodiyalathur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கொடியாலத்தூர் ",
  },
  {
    AC_NO: "174",
    POLL_NO: "132",
    POLL_NAME_EN: "Valivalam Desikar Higher Secondary School Valivalam",
    POLL_NAME_TA: "வலிவலம் தேசிகர்  மேல்நிலைப்பள்ளி, வலிவலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "133",
    POLL_NAME_EN: "Valivalam Desikar Higher Secondary School Valivalam",
    POLL_NAME_TA: "வலிவலம் தேசிகர் மேல்நிலைப்பள்ளி, வலிவலம்",
  },
  {
    AC_NO: "174",
    POLL_NO: "134",
    POLL_NAME_EN: "Kilvelur Panchayat Union Elementary School South Panaiyur",
    POLL_NAME_TA: "கீழ்வேளூர் ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, தெற்கு பனையூர் ",
  },
  {
    AC_NO: "177",
    POLL_NO: "1",
    POLL_NAME_EN: "Panchayat Union Primary  School, Mazhavarayanallur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, மழவராயநல்லூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "2",
    POLL_NAME_EN: "Panchayat Union  Primary  School Kunniyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, குன்னியூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "3",
    POLL_NAME_EN: "Panchayat Union  Primary  School Boothmangalam Pallivarthi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பூதமங்கலம் பள்ளி,வர்த்தி",
  },
  {
    AC_NO: "177",
    POLL_NO: "4",
    POLL_NAME_EN: "Panchayat Union  Primary  School Kulamanikkam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, குலமாணிக்கம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "5",
    POLL_NAME_EN: "Panchayat Union  Primary  School Senthangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, சேந்தங்குடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "6",
    POLL_NAME_EN: "Panchayat Union  Primary  School Seruvamani",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, செருவாமணி",
  },
  {
    AC_NO: "177",
    POLL_NO: "7",
    POLL_NAME_EN: "Panchayat Union  Primary  School Thirunallikkaval",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, திருநெல்லிக்காவல்",
  },
  {
    AC_NO: "177",
    POLL_NO: "8",
    POLL_NAME_EN: "Panchayat Union  Primary  School Mavadakudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, மாவட்டக்குடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "9",
    POLL_NAME_EN: "Government High School, Vikkirapandiyam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, விக்கிரபாண்டியம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "10",
    POLL_NAME_EN:
      "Panchayat Union  Primary  School Pariyakuvadi Senthamangalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பொரியகுருவாடி சேந்தமங்கலம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "11",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Nemmeli",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, நெம்மேலி",
  },
  {
    AC_NO: "177",
    POLL_NO: "12",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Ovarchery Kottur Thottam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஓவர்சேரி கோட்டூர் தோட்டம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "13",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Adhichapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஆதிச்சபுரம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "14",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Cheri",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, சேரி",
  },
  {
    AC_NO: "177",
    POLL_NO: "15",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Renganathapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ரெங்கநாதபுரம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "16",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Panaiyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பனையூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "17",
    POLL_NAME_EN: "Government Higher Sec  School, Kottur",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப் பள்ளி, கோட்டூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "18",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Kottur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கோட்டூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "19",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Irulnikki",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, இருள்நிக்கி",
  },
  {
    AC_NO: "177",
    POLL_NO: "20",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Puzhuthikudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, புழுதிக்குடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "21",
    POLL_NAME_EN:
      "Panchayat Union  Primary  School  Kumaramangalam Puzhuthikdi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, குமாரமங்கலம் புழுதிக்குடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "22",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Alathur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஆலாத்தூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "23",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Kaduvagudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, காடுவாகுடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "24",
    POLL_NAME_EN: "Panchayat Union   Middle    School  Vattar",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, வாட்டார்",
  },
  {
    AC_NO: "177",
    POLL_NO: "25",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Paingattur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பைங்காட்டூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "26",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Kurichimoolai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, குறிச்சிமூலை ",
  },
  {
    AC_NO: "177",
    POLL_NO: "27",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Orathur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஒரத்தூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "28",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Nallur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, நல்லூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "29",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Akkaraikottagam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, அக்கரைக்கோட்டம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "30",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Thirukkalar",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, திருக்களார்",
  },
  {
    AC_NO: "177",
    POLL_NO: "31",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Keeralathur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கீராலத்தூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "32",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Thiruthangoor",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, திருத்தங்கூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "33",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Natham Andangarai (P)",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, நத்தம் ஆண்டாங்கரை (ஊ)",
  },
  {
    AC_NO: "177",
    POLL_NO: "34",
    POLL_NAME_EN: "Ramakrishna Aided Primary   School  Ammanur",
    POLL_NAME_TA: "ராமகிருஷ்ணா உதவி துவக்கப்பள்ளி, அம்மனூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "35",
    POLL_NAME_EN: "Panchayat Union   Middle    School  Katchanam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப் பள்ளி, கச்சனம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "36",
    POLL_NAME_EN: "Nursery school Main Road Alathambadi",
    POLL_NAME_TA: "நர்சரிப்பள்ளி, மெயின் ரோடு ஆலத்தம்பாடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "37",
    POLL_NAME_EN: "Janaki Anni Government High School Ponnirai Alathambadi",
    POLL_NAME_TA: "ஜானகி அன்னி அரசினர் உயர்நிலைப்பள்ளி, பொன்னிரை ஆலத்தம்பாடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "38",
    POLL_NAME_EN: "Janaki Anni Government High School Ponnirai Alathambadi",
    POLL_NAME_TA: "ஜானகி அன்னி அரசினர் உயர்நிலைப்பள்ளி, பொன்னிரை ஆலத்தம்பாடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "39",
    POLL_NAME_EN: "Panchayat Union  Primary  School Alivalam Poosalangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஆலிவலம் பூசலாங்குடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "40",
    POLL_NAME_EN: "Panchayat Union   Middle    School  Vilakkudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, விளக்குடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "41",
    POLL_NAME_EN: "Government High School  Vilakkudi",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, விளக்குடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "42",
    POLL_NAME_EN: "Ramakrishna Aided Middle   School Rayanallur",
    POLL_NAME_TA: "இராமகிருஷ்ணா உதவிபெறும் நடுநிலைப்பள்ளி, ராயநல்லூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "43",
    POLL_NAME_EN: "Ramakrishna Aided Middle   School Rayanallur",
    POLL_NAME_TA: "இராமகிருஷ்ணா உதவிபெறும் நடுநிலைப்பள்ளி, ராயநல்லூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "44",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Panaiyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பனையூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "45",
    POLL_NAME_EN: "Panchayat Union  Primary  School Thirupatthur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, திருப்பத்தூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "46",
    POLL_NAME_EN: "St John-De-Britto High School Pallankovil",
    POLL_NAME_TA: "செயின்ட் ஜான் பிரிட்டோ உயர்நிலைப்பள்ளி, பள்ளங்கோவில",
  },
  {
    AC_NO: "177",
    POLL_NO: "47",
    POLL_NAME_EN: "St John-De-Britto High School Pallankovil",
    POLL_NAME_TA: "செயின்ட் ஜான் பிரிட்டோ உயர்நிலைப்பள்ளி, பள்ளங்கோவில",
  },
  {
    AC_NO: "177",
    POLL_NO: "48",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Rajakothamangalam (P)",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ராஜகொத்தமங்கலம் (ஊ)",
  },
  {
    AC_NO: "177",
    POLL_NO: "49",
    POLL_NAME_EN: "Rajagopal Aided Primary School Mettupalayam",
    POLL_NAME_TA: "இராசகோபால் உதவிபெறும் துவக்கப்பள்ளி, மேட்டுபாளையம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "50",
    POLL_NAME_EN: "Nakkiranar Aided Middle School Keerakalur",
    POLL_NAME_TA: "நக்கீரனார் உதவி பெறும் நடுநிலைப்பள்ளி, கீரக்களூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "51",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Thiruvazhanchuli",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, திருவலஞ்சுழி",
  },
  {
    AC_NO: "177",
    POLL_NO: "52",
    POLL_NAME_EN: " Panchayat Union  Primary  School   Palayangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பழையங்குடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "53",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Manali",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, மணலி",
  },
  {
    AC_NO: "177",
    POLL_NO: "54",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Kurumbal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, குரும்பல்",
  },
  {
    AC_NO: "177",
    POLL_NO: "55",
    POLL_NAME_EN: "Panchayat Union   Middle    School  Kunnur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, குன்னூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "56",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Varambiyam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, வரம்பியம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "57",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Deevammapuram  Varambiyam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, தீவம்மாபுரம் வரம்பியம் ",
  },
  {
    AC_NO: "177",
    POLL_NO: "58",
    POLL_NAME_EN: "Valluvar Aided Primary   School  Deevammapuram  Varambiyam",
    POLL_NAME_TA: "வள்ளுவர் உதவிபெறும் துவக்கபள்ளி, தீவம்மாபுரம் வரம்பியம் ",
  },
  {
    AC_NO: "177",
    POLL_NO: "59",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Nunakkadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, நுனாக்காடு",
  },
  {
    AC_NO: "177",
    POLL_NO: "60",
    POLL_NAME_EN: "Panchayat Union  Primary  School   Ezhilur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, எழிலூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "61",
    POLL_NAME_EN: "Government High School  Nedumbalam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, நெடும்பலம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "62",
    POLL_NAME_EN: "Panchayat Union council hall  Thiruthuraipoondi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய கவுண்சில் ஹால் திருத்துறைப்பூண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "63",
    POLL_NAME_EN:
      "St. Therasa Girls Higher Secondary School Thiruthiraipoondi ",
    POLL_NAME_TA: "புனித தெரசாள் பெண்கள் மேல்நிலைப்பள்ளி, திருத்துறைப்பூண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "64",
    POLL_NAME_EN:
      "St. Therasa Girls Higher Secondary School Thiruthiraipoondi ",
    POLL_NAME_TA: "புனித தெரசாள் பெண்கள் மேல்நிலைப்பள்ளி, திருத்துறைப்பூண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "65",
    POLL_NAME_EN: "P W Office   Thiruthiraipoondi",
    POLL_NAME_TA: "பி டபிள்யூ அலுவலகம் திருத்துறைப்பூண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "66",
    POLL_NAME_EN:
      "Government   Adi-dravidar. Welfare  School   Thiruthuraipoondi  ",
    POLL_NAME_TA: "அரசினர் ஆதிதிராவிடர் நலப்பள்ளி, திருத்துறைப்பூண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "67",
    POLL_NAME_EN:
      "Government   Adi-dravidar. Welfare Primary School Abishekakattalai",
    POLL_NAME_TA: "அரசினர் ஆதிதிராவிடர் நல துவக்கப்பள்ளி, அபிஷேககட்டளை",
  },
  {
    AC_NO: "177",
    POLL_NO: "68",
    POLL_NAME_EN: "St. Antony's Aided Primary School Thiruthuraipoondi",
    POLL_NAME_TA: "புனித அந்தோணி உதவிபெறும் துவக்கப்பள்ளி, திருத்துறைப்பூண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "69",
    POLL_NAME_EN: "Panchayat Union   Middle    School  Thiruthuraipoondi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, திருத்துறைப்பூண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "70",
    POLL_NAME_EN: "Government  Higher Secondary School Thiruthuraipoondi",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, திருத்துறைப்பூண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "71",
    POLL_NAME_EN: "Government Boys   Higher Secondary School Thiruthuraipoondi",
    POLL_NAME_TA: "அரசினர் ஆண்கள் மேல்நிலைப்பள்ளி, திருத்துறைப்பூண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "72",
    POLL_NAME_EN:
      "Victory Aided Primary School,Singalanthi, Thiruthuraipoondi ",
    POLL_NAME_TA: "விக்டரி உதவி துவக்கப்பள்ளி, சிங்களாந்தி திருத்துறைப்பூண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "73",
    POLL_NAME_EN: "Aided Primary School Velur",
    POLL_NAME_TA: "உதவித் துவக்கப்பள்ளி, வேளூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "74",
    POLL_NAME_EN: "Aided Primary School Kokkaladi",
    POLL_NAME_TA: "உதவிபெறும் துவக்கப்பள்ளி, கொக்காலடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "75",
    POLL_NAME_EN: "Thiruvalluvar Arul Neri Aided Middle School Korukai ",
    POLL_NAME_TA: "திருவள்ளுவர் அருள்நெறி உதவிநடுநிலைப்பள்ளி, கொருக்கை",
  },
  {
    AC_NO: "177",
    POLL_NO: "76",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Thalaikkadu Korukkai (P)",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, தலைக்காடு கொருக்கை (ஊ",
  },
  {
    AC_NO: "177",
    POLL_NO: "77",
    POLL_NAME_EN: "Government High School  Pamani",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, பாமணி",
  },
  {
    AC_NO: "177",
    POLL_NO: "78",
    POLL_NAME_EN: "Government High School  Pamani",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, பாமணி",
  },
  {
    AC_NO: "177",
    POLL_NO: "79",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Pamani",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பாமணி",
  },
  {
    AC_NO: "177",
    POLL_NO: "80",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Madapuram Segal (P)",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, மடப்புரம் சேகல் (ஊ)",
  },
  {
    AC_NO: "177",
    POLL_NO: "81",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Adhirengam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஆதிரெங்கம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "82",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Kattimedu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கட்டிமேடு",
  },
  {
    AC_NO: "177",
    POLL_NO: "83",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Pitchankottagam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பிச்சன்கோட்டகம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "84",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Melamaruthur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, மேலமருதூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "85",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Mangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, மாங்குடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "86",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Maruthavanam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, மருதவனம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "87",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Vanganagar",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, வங்கநகர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "88",
    POLL_NAME_EN: "Panchayat Union Middle  School  Ariyalur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, ஆரியலூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "89",
    POLL_NAME_EN: "Panchayat Union Middle  School  Kallikudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, ஓவரூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "90",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Kallikudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கள்ளிக்குடி",
  },
  {
    AC_NO: "177",
    POLL_NO: "91",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Pandi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, பாண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "92",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Veppanchery Keelapandi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, வேப்பஞ்சேரி கீழப்பாண்டி",
  },
  {
    AC_NO: "177",
    POLL_NO: "93",
    POLL_NAME_EN: "Panchayat Union  Primary  School kudisethi Kunnalaur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, குடிசேத்தி குன்னலூர் ",
  },
  {
    AC_NO: "177",
    POLL_NO: "94",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Ekkal Kunnalur (P)",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, எக்கல் குன்னலூர் (ஊ)",
  },
  {
    AC_NO: "177",
    POLL_NO: "95",
    POLL_NAME_EN: "Government High School  Edaiyur",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, எடையூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "96",
    POLL_NAME_EN: "Government High School  Edaiyur",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, எடையூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "97",
    POLL_NAME_EN: "Government High School  Edaiyur",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, எடையூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "98",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Sanganthi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, சங்கந்தி",
  },
  {
    AC_NO: "177",
    POLL_NO: "99",
    POLL_NAME_EN: "Panchayat Union  Primary  School  vadasanganthi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, வடசங்கந்தி",
  },
  {
    AC_NO: "177",
    POLL_NO: "100",
    POLL_NAME_EN: "Panchayat Union Middle  School  Tholi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, தோலி",
  },
  {
    AC_NO: "177",
    POLL_NO: "101",
    POLL_NAME_EN: "Panchayat Union Middle  School  Tholi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, தோலி",
  },
  {
    AC_NO: "177",
    POLL_NO: "102",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Alkaduveli Pinnathur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, ஆள்காட்டுவெளி பின்னத்தூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "103",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Udhayamarthandapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, உதயமார்த்தாண்டபுரம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "104",
    POLL_NAME_EN:
      "Panchayat Union  Primary  School  Natchikulam Udhayamarthandapuram",
    POLL_NAME_TA:
      "ஊராட்சி ஒன்றிய துவக்கபள்ளி, நாச்சிக்குளம் உதயமார்த்தாண்டபுரம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "105",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Udhayamarthandapuram (P)",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, உதயமார்த்தாண்டபுரம் (ஊ)",
  },
  {
    AC_NO: "177",
    POLL_NO: "106",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Gopalasamuthiram Uppur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, கோபாலசமுத்திரம் உப்பூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "107",
    POLL_NAME_EN: "Venkadeshwar Aided Primary  School   Uppur",
    POLL_NAME_TA: "வெங்கடேஸ்வரா உதவி துவக்கபள்ளி, உப்பூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "108",
    POLL_NAME_EN: "Panchayat Union Middle  School  Alangadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, ஆலங்காடு",
  },
  {
    AC_NO: "177",
    POLL_NO: "109",
    POLL_NAME_EN: "Panchayat Union Middle  School  Alangadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, ஆலங்காடு",
  },
  {
    AC_NO: "177",
    POLL_NO: "110",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Vadakadukovilur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, வடகாடுகோவிலூர்",
  },
  {
    AC_NO: "177",
    POLL_NO: "111",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Keelanammankurichi ",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, கீழ்நம்மங்குறிச்சி ",
  },
  {
    AC_NO: "177",
    POLL_NO: "112",
    POLL_NAME_EN:
      "Panchayat Union  Primary  School  Keelanammankurichi  Mangal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, கீழ்நம்மங்குறிச்சி மங்கல்",
  },
  {
    AC_NO: "177",
    POLL_NO: "113",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Melanammankurichi ",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, மேலநம்மங்குறிச்சி",
  },
  {
    AC_NO: "177",
    POLL_NO: "114",
    POLL_NAME_EN: "Panchayat Union Middle  School  Keelakadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கீழக்காடு",
  },
  {
    AC_NO: "177",
    POLL_NO: "115",
    POLL_NAME_EN: "Panchayat Union Middle  School  Keelakadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கீழக்காடு",
  },
  {
    AC_NO: "177",
    POLL_NO: "116",
    POLL_NAME_EN:
      "Periyanayaki  Government Girls higher secondary school Muthupettai",
    POLL_NAME_TA: "பொயிநாயகி அரசினர் பெண்கள் மேல்நிலைப்பள்ளி, முத்துப்பேட்டை",
  },
  {
    AC_NO: "177",
    POLL_NO: "117",
    POLL_NAME_EN:
      "Periyanayaki  Government Girls higher secondary school Muthupettai",
    POLL_NAME_TA: "பொயிநாயகி அரசினர் பெண்கள் மேல்நிலைப்பள்ளி, முத்துப்பேட்டை",
  },
  {
    AC_NO: "177",
    POLL_NO: "118",
    POLL_NAME_EN: "Panchayat Union council hall  Muthupettai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய கவுன்சில் ஹால் முத்துப்பேட்டை",
  },
  {
    AC_NO: "177",
    POLL_NO: "119",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Muthupettai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றியதுவக்கப்பள்ளி, முத்துப்பேட்டை",
  },
  {
    AC_NO: "177",
    POLL_NO: "120",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Muthupettai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கபள்ளி, முத்துப்பேட்டை",
  },
  {
    AC_NO: "177",
    POLL_NO: "121",
    POLL_NAME_EN: "A.N Aided  Primary  School  Muthupettai",
    POLL_NAME_TA: "ஏ ஏன் உதவி துவக்கப்பள்ளி, முத்துப்பேட்டை",
  },
  {
    AC_NO: "177",
    POLL_NO: "122",
    POLL_NAME_EN: "A.N Aided  Primary  School  Muthupettai",
    POLL_NAME_TA: "ஏ ஏன் உதவி துவக்கப்பள்ளி, முத்துப்பேட்டை",
  },
  {
    AC_NO: "177",
    POLL_NO: "123",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Muthupettai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, முத்துப்பேட்டை",
  },
  {
    AC_NO: "177",
    POLL_NO: "124",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Muthupettai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, முத்துப்பேட்டை",
  },
  {
    AC_NO: "177",
    POLL_NO: "125",
    POLL_NAME_EN: "Panchayat Union  Primary  School Jambuvanodi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, ஜாம்புவானோடை",
  },
  {
    AC_NO: "177",
    POLL_NO: "126",
    POLL_NAME_EN: "Panchayat Union Middle  School  Vadakadu Jambuvanodi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, வடகாடு ஜாம்புவானோடை ",
  },
  {
    AC_NO: "177",
    POLL_NO: "127",
    POLL_NAME_EN: "Panchayat Union  Primary  School Kalladikollai Jambuvanodi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கல்லடிக்கொல்லை ஜாம்புவானோடை",
  },
  {
    AC_NO: "177",
    POLL_NO: "128",
    POLL_NAME_EN: "Panchayat Union  Primary  School Therkkukadu Jambuvanodi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, தெற்குகாடு ஜாம்புவானோடை",
  },
  {
    AC_NO: "177",
    POLL_NO: "129",
    POLL_NAME_EN: "Government High School  Thillaivilagam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, தில்லைவிளாகம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "130",
    POLL_NAME_EN: "Panchayat Union  Primary  School Thillaivilagam(P)",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, தில்லைவிளாகம் (ஊ)",
  },
  {
    AC_NO: "177",
    POLL_NO: "131",
    POLL_NAME_EN: "Panchayat Union  Primary  School Therkkukadu Thillaivilagam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, தெற்குக்காடு தில்லைவிளாகம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "132",
    POLL_NAME_EN: "Panchayat Union  Primary  School Chengankadu Thillaivilagam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, செங்காடு தில்லைவிளாகம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "133",
    POLL_NAME_EN: "Government High School  Mangalanayagi Idumbavanam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, மங்களநாயகிபுரம் இடும்பாவனம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "134",
    POLL_NAME_EN:
      "Panchayat Union  Primary  School Keelavadiyakadu Idumbavanam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கீழவாடியக்காடு இடும்பாவனம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "135",
    POLL_NAME_EN: "Panchayat Union  Primary  School Melavadiyakadu Idumbavanam",
    POLL_NAME_TA: "ஊராட்சி  ஒன்றிய துவக்கப்பள்ளி, மேலவாடியக்காடு இடும்பாவனம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "136",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Melaperumalai",
    POLL_NAME_TA: "ஊராட்சி  ஒன்றிய துவக்கப்பள்ளி, மேலப்பெருமழை",
  },
  {
    AC_NO: "177",
    POLL_NO: "137",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Keelaperumalai",
    POLL_NAME_TA: "ஊராட்சி  ஒன்றிய துவக்கப்பள்ளி, கீழப்பெருமழை",
  },
  {
    AC_NO: "177",
    POLL_NO: "138",
    POLL_NAME_EN:
      "Panchayat Union  Primary  School  Karpaganatharkulam Vilangadu",
    POLL_NAME_TA: "ஊராட்சி  ஒன்றிய துவக்கப்பள்ளி, கற்பகநாதர்குளம் விளாங்காடு",
  },
  {
    AC_NO: "177",
    POLL_NO: "139",
    POLL_NAME_EN: "Elango Aided  Primary  School  Karpaganatharkulam ",
    POLL_NAME_TA: "இளங்கோ உதவிபெறும் துவக்கப் பள்ளி, கற்பகநாதர் குளம்",
  },
  {
    AC_NO: "177",
    POLL_NO: "140",
    POLL_NAME_EN: "Panchayat Union  Primary  School  Munankadu Thondiyakadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, முனாங்காடு தொண்டியக்காடு",
  },
  {
    AC_NO: "177",
    POLL_NO: "141",
    POLL_NAME_EN:
      "Panchayat Union  Primary  School  Keelathondiyakadu Thondiyakadu",
    POLL_NAME_TA:
      "ஊராட்சி ஒன்றிய துவக்கப்பள்ளி, கீழ்தொண்டியக்காடு தொண்டியக்காடு",
  },
  {
    AC_NO: "178",
    POLL_NO: "1",
    POLL_NAME_EN: "Panchayat Union Primary School Paruthikottai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, பருத்திக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "2",
    POLL_NAME_EN: "Panchayat Union Primary  School Muvanallur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, மூவாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "3",
    POLL_NAME_EN: "Panchayat Union Primary  School Karnavur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, கர்ணாவூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "4",
    POLL_NAME_EN: "Panchayat Union Primary  School Pamani",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, பாமணி",
  },
  {
    AC_NO: "178",
    POLL_NO: "5",
    POLL_NAME_EN: "Panchayat Union Primary  School Vetthittal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, வேட்டைத்திடல்",
  },
  {
    AC_NO: "178",
    POLL_NO: "6",
    POLL_NAME_EN: "Government Adi Dravidar Welfare Middle School Savalakkaran",
    POLL_NAME_TA: "அரசினர் ஆதிதிராவிடர் நல நடுநிலைப்பள்ளி, சவளக்காரன்",
  },
  {
    AC_NO: "178",
    POLL_NO: "7",
    POLL_NAME_EN: "Panchayat Union Primary  School Vadagovanur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, வடகோவனூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "8",
    POLL_NAME_EN: "Panchayat Union Middle School Marakkadai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, மரக்கடை",
  },
  {
    AC_NO: "178",
    POLL_NO: "9",
    POLL_NAME_EN: "Koothanallur Municipal Office Koothanallur",
    POLL_NAME_TA: "கூத்தாநல்லூர் நகராட்சி அலுவலகம், கூத்தாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "10",
    POLL_NAME_EN: "Koothanallur Municipal Office Koothanallur",
    POLL_NAME_TA: "கூத்தாநல்லூர் நகராட்சி அலுவலகம், கூத்தாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "11",
    POLL_NAME_EN: "Koothanallur Municipal Office Koothanallur",
    POLL_NAME_TA: "கூத்தாநல்லூர் நகராட்சி அலுவலகம் கூத்தாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "12",
    POLL_NAME_EN: "Government Higher Secondary School Koothanallur",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, கூத்தாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "13",
    POLL_NAME_EN: "Alathan Aided Primary School Nagangudi Koothanallur",
    POLL_NAME_TA: "அலதஃன் உதவிபெறும் தொடக்கபள்ளி, நாகங்குடி கூத்தாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "14",
    POLL_NAME_EN: "Government Girls High School Koothanallur",
    POLL_NAME_TA: "அரசு பெண்கள் உயர்நிலைப்பள்ளி, கூத்தாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "15",
    POLL_NAME_EN: "Government Girls High School Koothanallur",
    POLL_NAME_TA: "அரசு பெண்கள் உயர்நிலைப்பள்ளி, கூத்தாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "16",
    POLL_NAME_EN: "Jamia Primary School Koothanallur",
    POLL_NAME_TA: "ஜாமியா தொடக்கபள்ளி, கூத்தாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "17",
    POLL_NAME_EN: "Manpa Ul Ula Middle School Koothanallur",
    POLL_NAME_TA: "மன்பா உல் உலா நடுநிலைப்பள்ளி, கூத்தாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "18",
    POLL_NAME_EN: "Manpa Ul Ula Middle School Koothanallur",
    POLL_NAME_TA: "மன்பா உல் உலா நடுநிலைப்பள்ளி, கூத்தாநல்லூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "19",
    POLL_NAME_EN: "Panchayat Union  Middle School Marakkadai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, மரக்கடை",
  },
  {
    AC_NO: "178",
    POLL_NO: "20",
    POLL_NAME_EN: "Panchayat Union  Middle School Poothamangalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, பூதமங்கலம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "21",
    POLL_NAME_EN: "Panchayat Union  Middle School Poothamangalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, பூதமங்கலம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "22",
    POLL_NAME_EN: "Panchayat Union  Middle School Velukudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, வேளுக்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "23",
    POLL_NAME_EN: "Panchayat Union  Middle School Velukudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, வேளுக்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "24",
    POLL_NAME_EN: "Panchayat Union  Primary School Venkaram Peraiyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, வெங்காரம் பேரையூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "25",
    POLL_NAME_EN: "Panchayat Union  Primary School Poonthalangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, பூந்தாழங்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "26",
    POLL_NAME_EN: "Panchayat Union  Primary School Keelamanali",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, கீழமணலி",
  },
  {
    AC_NO: "178",
    POLL_NO: "27",
    POLL_NAME_EN: "Panchayat Union  Primary School Okaiperaiyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, ஓகைபேரையூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "28",
    POLL_NAME_EN: "Panchayat Union  Primary School Arichandrapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, அரிசந்திரபுரம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "29",
    POLL_NAME_EN: "Government High School Pullamangalam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, புள்ளமங்கலம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "30",
    POLL_NAME_EN: "Panchayat Union  Primary School Thirunattiyathangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, திருநாட்டியத்தாங்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "31",
    POLL_NAME_EN: "Panchayat Union  Primary School Chithiraiyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, சித்திரையூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "32",
    POLL_NAME_EN: "Panchayat Union  Primary School Manakarai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, மணக்கரை",
  },
  {
    AC_NO: "178",
    POLL_NO: "33",
    POLL_NAME_EN: "Panchayat Union  Primary School Poikottur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, பொயிகொத்தூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "34",
    POLL_NAME_EN: "Panchayat Union  Middle School Vadapadhimangalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, வடபாதிமங்கலம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "35",
    POLL_NAME_EN: "Panchayat Union  Middle School Vadapadhimangalam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, வடபாதிமங்கலம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "36",
    POLL_NAME_EN: "Venu Wodeyar Middle School Palayanur",
    POLL_NAME_TA: "வேணு உடையார் நடுநிலைப்பள்ளி, பழையனூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "37",
    POLL_NAME_EN: "Panchayat Union  Primary School Palayanur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, பழையனூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "38",
    POLL_NAME_EN: "Panchayat Union  Primary School Thaneerkunnam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, தண்ணீர்குன்னம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "39",
    POLL_NAME_EN: "Panchayat Union  Primary School Pandukudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, பாண்டுக்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "40",
    POLL_NAME_EN: "Township Union Middle School Thirurameswaram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, திருராமேஸ்வரம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "41",
    POLL_NAME_EN: "Panchayat Union  Primary School Tenkovanur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, தென்கோவனூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "42",
    POLL_NAME_EN: "Panchayat Union  Primary School Vanjiyur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, வாஞ்சியூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "43",
    POLL_NAME_EN: "Panchayat Union  Primary School Kasangulam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, காசாங்குளம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "44",
    POLL_NAME_EN: "Municipal Jainatheru Primary School Mannargudi ",
    POLL_NAME_TA: "நகராட்சி ஜெயினத்தெரு தொடக்கப்பள்ளி, மன்னார்குடி ",
  },
  {
    AC_NO: "178",
    POLL_NO: "45",
    POLL_NAME_EN: "Punitha Susaiyappar Middle School Mannargudi ",
    POLL_NAME_TA: "புனித சூசையப்பர் நடுநிலைப்பள்ளி, மன்னார்குடி ",
  },
  {
    AC_NO: "178",
    POLL_NO: "46",
    POLL_NAME_EN: "Municipal Jayankondanathar Primary School Mannargudi ",
    POLL_NAME_TA: "நகராட்சி ஜெயங்கொண்டநாதர் தொடக்கப்பள்ளி, மன்னார்குடி ",
  },
  {
    AC_NO: "178",
    POLL_NO: "47",
    POLL_NAME_EN: "Municipal Rajampalayam Middle School Mannargudi",
    POLL_NAME_TA: "நகராட்சி இராஜம்பாளையம் நடுநிலைப்பள்ளி, மன்னார்குடி ",
  },
  {
    AC_NO: "178",
    POLL_NO: "48",
    POLL_NAME_EN: "Municipal Rajampalayam Middle School Mannargudi",
    POLL_NAME_TA: "நகராட்சி இராஜம்பாளையம் நடுநிலைப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "49",
    POLL_NAME_EN: "Municipal Rajampalayam Middle School Mannargudi",
    POLL_NAME_TA: "நகராட்சி இராஜம்பாளையம் நடுநிலைப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "50",
    POLL_NAME_EN:
      "Adhiparasakthi Educational Corporation High School Mannargudi",
    POLL_NAME_TA: "ஆதிபராசக்தி கல்வியியல் கழக உயர்நிலைப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "51",
    POLL_NAME_EN: "Findlay Higher Secondary School Mannargudi",
    POLL_NAME_TA: "பின்லே மேல்நிலைப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "52",
    POLL_NAME_EN: "Municipal Model Middle School Mannargudi",
    POLL_NAME_TA: "நகராட்சி மாடல் நடுநிலைப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "53",
    POLL_NAME_EN: "National Primary School Mannargudi",
    POLL_NAME_TA: "தேசிய தொடக்கபள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "54",
    POLL_NAME_EN: "Prakasam Primary School Mannargudi",
    POLL_NAME_TA: "பிரகாசம் தொடக்கபள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "55",
    POLL_NAME_EN: "Municipal Keezharaja Veethi Primary School Mannargudi",
    POLL_NAME_TA: "நகராட்சி கீழராஜ வீதி தொடக்கபள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "56",
    POLL_NAME_EN: "C.S.I Napier Primary School Mannargudi",
    POLL_NAME_TA: "சி ஏஸ் ஐ நேப்பியர் தொடக்கபள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "57",
    POLL_NAME_EN: "Manimekalai Middle School Mannargudi",
    POLL_NAME_TA: "மணிமேகலை நடுநிலைப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "58",
    POLL_NAME_EN: "Panchayat Union Middle School Mannargudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "59",
    POLL_NAME_EN: "St joseph Girls' Higher Secondary School Mannargudi",
    POLL_NAME_TA: "புனித சூசையப்பர் மகளியர் மோ்நிலைப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "60",
    POLL_NAME_EN: "Panchayat Union Office Mannargudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய அலுவலகம் மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "61",
    POLL_NAME_EN: "Municipal Gopalasamudram Middle School Mannargudi",
    POLL_NAME_TA: "நகராட்சி கோபாலசமுத்திரம் நடுநிலைப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "62",
    POLL_NAME_EN: "Municipal Cooperative Urban Bank Primary School Mannargudi",
    POLL_NAME_TA: "நகராட்சி கூட்டுறவு அர்பன் பேங்க் தொடக்கப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "63",
    POLL_NAME_EN: "Municipal Cooperative Urban Bank Primary School Mannargudi",
    POLL_NAME_TA: "நகராட்சி கூட்டுறவு அர்பன் பேங்க் தொடக்கப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "64",
    POLL_NAME_EN: "Municipal Cooperative Urban Bank Primary School Mannargudi",
    POLL_NAME_TA: "நகராட்சி கூட்டுறவு அர்பன் பேங்க் தொடக்கப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "65",
    POLL_NAME_EN: "Government Girls' Higher Secondary School",
    POLL_NAME_TA: "அரசினர் மகளிர் மேல்நிலைப்பள்ளி,",
  },
  {
    AC_NO: "178",
    POLL_NO: "66",
    POLL_NAME_EN: "Municipal Pendland Model Primary School Mannargudi",
    POLL_NAME_TA: "நகராட்சி பெண்ட்லண்டு மாடல் தொடக்கப்பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "67",
    POLL_NAME_EN: "Western Model Primary School Mannargudi",
    POLL_NAME_TA: "வெஸ்டர்ன் மாடல் தொடக்கபள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "68",
    POLL_NAME_EN: "St joseph Matriculation School Mannargudi",
    POLL_NAME_TA: "தூய புனித சூசையப்பர் மெட்ரிகுலேஷன் பள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "69",
    POLL_NAME_EN: "Findlay Primary School Mannargudi",
    POLL_NAME_TA: "பின்லே தொடக்கபள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "70",
    POLL_NAME_EN: "Findlay Primary School Mannargudi",
    POLL_NAME_TA: "பின்லே தொடக்கபள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "71",
    POLL_NAME_EN: "Findlay Primary School Mannargudi",
    POLL_NAME_TA: "பின்லே தொடக்கபள்ளி, மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "72",
    POLL_NAME_EN: "Sokkanathar Meenakshi Amman Temple Hall Mannargudi",
    POLL_NAME_TA: "சொக்கநாதர் மீனாட்சியம்மன் கோவில் மண்டபம், மன்னார்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "73",
    POLL_NAME_EN: "Thirumurugan High School Melavasal",
    POLL_NAME_TA: "திருமுருகன் உயர்நிலைப்பள்ளி, மேலவாசல்",
  },
  {
    AC_NO: "178",
    POLL_NO: "74",
    POLL_NAME_EN: "Panchayat Union Primary School Edayar Embethi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஏடையர் ஏம்பேத்தி",
  },
  {
    AC_NO: "178",
    POLL_NO: "75",
    POLL_NAME_EN: "Panchayat Union Primary School Karikottai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, காரிக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "76",
    POLL_NAME_EN: "Panchayat Union Middle School Neduvakottai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, நெடுவாக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "77",
    POLL_NAME_EN: "Panchayat Union Primary School Melanagai",
    POLL_NAME_TA: "உராட்சி ஒன்றிய தொடக்கப்பள்ளி, மேலநாகை",
  },
  {
    AC_NO: "178",
    POLL_NO: "78",
    POLL_NAME_EN: "Panchayat Union Primary School Keelanattam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, கீழநத்தம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "79",
    POLL_NAME_EN: "Panchayat Union Primary School Assesham",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, அசேஷம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "80",
    POLL_NAME_EN: "Panchayat Union Primary School Melamaravakkadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, மேலமரவாக்காடு",
  },
  {
    AC_NO: "178",
    POLL_NO: "81",
    POLL_NAME_EN: "Panchayat Union Middle School Serankulam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, சேரங்குளம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "82",
    POLL_NAME_EN: "Panchayat Union Middle School Serankulam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, சேரங்குளம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "83",
    POLL_NAME_EN: "Panchayat Union Primary School Nemmeli",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, நெம்மேலி",
  },
  {
    AC_NO: "178",
    POLL_NO: "84",
    POLL_NAME_EN: "Panchayat Union Primary School Maravakkadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, மரவாக்காடு",
  },
  {
    AC_NO: "178",
    POLL_NO: "85",
    POLL_NAME_EN: "Panchayat Union Primary School Vadapathi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, வடபாதி",
  },
  {
    AC_NO: "178",
    POLL_NO: "86",
    POLL_NAME_EN: "Panchayat Union Primary School Thenpathi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, தென்பாதி",
  },
  {
    AC_NO: "178",
    POLL_NO: "87",
    POLL_NAME_EN: "Panchayat Union Primary School Ethakudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ஏத்தக்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "88",
    POLL_NAME_EN: "Meenakshi Mariappar High School Cholapandi",
    POLL_NAME_TA: "மீனாட்சி மாரியப்பர் உயர்நிலைப்பள்ளி, சோழபாண்டி",
  },
  {
    AC_NO: "178",
    POLL_NO: "89",
    POLL_NAME_EN: "Panchayat Union Primary School Rajagopalapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, ராஜகோபாலபுரம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "90",
    POLL_NAME_EN: "Panchayat Union Primary School Bainganadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, பைங்காநாடு",
  },
  {
    AC_NO: "178",
    POLL_NO: "91",
    POLL_NAME_EN: "Panchayat Union Primary School Bainganadu",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, பைங்காநாடு",
  },
  {
    AC_NO: "178",
    POLL_NO: "92",
    POLL_NAME_EN: "Panchayat Union Middle School Thulasendrapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, துளசேந்திரபுரம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "93",
    POLL_NAME_EN: "Panchayat Union Middle School Thulasendrapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, துளசேந்திரபுரம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "94",
    POLL_NAME_EN: "Panchayat Union Middle School Kandithampettai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, கண்டிதம்பேட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "95",
    POLL_NAME_EN: "Panchayat Union Primary School Sundarakottai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, சுந்தரக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "96",
    POLL_NAME_EN: "Panchayat Union Primary School Melathiruppalakkudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, மேலதிருப்பாலக்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "97",
    POLL_NAME_EN: "Thiruvalluvar Higher Secondary School Alangkottai",
    POLL_NAME_TA: "திருவள்ளுவர் மேல்நிலைப்பள்ளி, ஆலங்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "98",
    POLL_NAME_EN: "Panchayat Union Primary School Keezhathiruppalakkudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கப்பள்ளி, கீழ திருப்பாலக்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "99",
    POLL_NAME_EN: "Panchayat Union Middle School Melanemmeli",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, மேலநெம்மேலி",
  },
  {
    AC_NO: "178",
    POLL_NO: "100",
    POLL_NAME_EN: "Government High School Mahadevapattinam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, மகாதேவப்பட்டிணம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "101",
    POLL_NAME_EN: "Government High School Mahadevapattinam",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, மகாதேவப்பட்டிணம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "102",
    POLL_NAME_EN: "Government Higher Secondary School Ullikottai",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, உள்ளிக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "103",
    POLL_NAME_EN: "Government Higher Secondary School Ullikottai",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, உள்ளிக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "104",
    POLL_NAME_EN: "Panchayat Union Primary School Ullikottai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, உள்ளிகோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "105",
    POLL_NAME_EN: "Panchayat Union Primary School Koopachickottai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, கூப்பாச்சிக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "106",
    POLL_NAME_EN: "Government Higher Secondary School Paravakottai",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, பரவாக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "107",
    POLL_NAME_EN: "Government Higher Secondary School Paravakottai",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, பரவாக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "108",
    POLL_NAME_EN: "Panchayat Union Primary School Paravakottai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, பரவாக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "109",
    POLL_NAME_EN: "Panchayat Union Primary School Paravakottai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, பரவாக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "110",
    POLL_NAME_EN: "Government Higher Secondary School Paravakottai",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, பரவாக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "111",
    POLL_NAME_EN: "Panchayat Union Middle School, Melanatham",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, மேலநத்தம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "112",
    POLL_NAME_EN: "Government Higher Secondary School, Thirumakkottai",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, திருமக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "113",
    POLL_NAME_EN: "Panchayat Union Primary School, Thirumakkottai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, திருமக்கோட்டை",
  },
  {
    AC_NO: "178",
    POLL_NO: "114",
    POLL_NAME_EN: "Panchayat Union Primary School, Vallur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, வள்ளூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "115",
    POLL_NAME_EN: "Government Higher Secondary School, Radhanarasimapuram",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, ராதாநரசிம்மபுரம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "116",
    POLL_NAME_EN: "Panchayat Union Primary School, Thenparai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, தென்பரை",
  },
  {
    AC_NO: "178",
    POLL_NO: "117",
    POLL_NAME_EN: "Panchayat Union Primary School, Thenparai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, தென்பரை",
  },
  {
    AC_NO: "178",
    POLL_NO: "118",
    POLL_NAME_EN: "Panchayat Union Primary School, Keluvathur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, கெழுவத்தூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "119",
    POLL_NAME_EN: "Panchayat Union Primary School, Venkathangudi",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, வெங்கத்தாங்குடி",
  },
  {
    AC_NO: "178",
    POLL_NO: "120",
    POLL_NAME_EN: "Government  High School Kalappal",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, களப்பால்",
  },
  {
    AC_NO: "178",
    POLL_NO: "121",
    POLL_NAME_EN: "Panchayat Union Primary School Narayanapuram Kalappal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, நாராயணபுரம் களப்பாள்",
  },
  {
    AC_NO: "178",
    POLL_NO: "122",
    POLL_NAME_EN: "Panchayat Union Primary School Kulamanickam",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, குலமாணிக்கம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "123",
    POLL_NAME_EN: "Panchayat Union Primary School Naduvalikalappal",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, நடுவளிக்களப்பால்",
  },
  {
    AC_NO: "178",
    POLL_NO: "124",
    POLL_NAME_EN: "Panchayat Union Middle School  Therkunanalur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, தெற்குநாணலூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "125",
    POLL_NAME_EN: "Government High School Palaiyur",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, பாலையூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "126",
    POLL_NAME_EN: "Panchayat Union Middle School Palaikottai Parasapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய நடுநிலைப்பள்ளி, பாலையக்கோட்டை பரசபுரம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "127",
    POLL_NAME_EN: "Panchayat Union Primary School Elavanur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, எளவனூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "128",
    POLL_NAME_EN: "Panchayat Union Primary School Edachimulai",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, ஏடச்சிமுலை",
  },
  {
    AC_NO: "178",
    POLL_NO: "129",
    POLL_NAME_EN: "Panchayat Union Higher Secondary School Perugavazhnthan",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, பெருகவாழ்ந்தான்",
  },
  {
    AC_NO: "178",
    POLL_NO: "130",
    POLL_NAME_EN: "Panchayat Union Higher Secondary School Perugavazhnthan",
    POLL_NAME_TA: "அரசினர் மேல்நிலைப்பள்ளி, பெருகவாழ்ந்தான்",
  },
  {
    AC_NO: "178",
    POLL_NO: "131",
    POLL_NAME_EN: "Panchayat Union Primary School Mannukumundan",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, மண்ணுக்முண்டான்",
  },
  {
    AC_NO: "178",
    POLL_NO: "132",
    POLL_NAME_EN: "Panchayat Union Primary School Mannukumundan",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, மண்ணுக்முண்டான்",
  },
  {
    AC_NO: "178",
    POLL_NO: "133",
    POLL_NAME_EN: "Panchayat Union Primary School Karnavur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, கர்ணாவூர்",
  },
  {
    AC_NO: "178",
    POLL_NO: "134",
    POLL_NAME_EN: "Panchayat Union High School puthagaram",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, புத்தகரம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "135",
    POLL_NAME_EN: "Panchayat Union High School puthagaram",
    POLL_NAME_TA: "அரசினர் உயர்நிலைப்பள்ளி, புத்தகரம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "136",
    POLL_NAME_EN: "Panchayat Union Primary School Sithamalli",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, சித்தமல்லி",
  },
  {
    AC_NO: "178",
    POLL_NO: "137",
    POLL_NAME_EN: "Panchayat Union Primary School Balakrishnapuram",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, பாலகிருஷ்ணபுரம்",
  },
  {
    AC_NO: "178",
    POLL_NO: "138",
    POLL_NAME_EN: "Panchayat Union Primary School Serukalathur",
    POLL_NAME_TA: "ஊராட்சி ஒன்றிய தொடக்கபள்ளி, செருகளத்தூர்",
  },
];
